export enum wsEvents {
  connection = "connection",
  connectionError = "connect_error",
  peerDisconnect = "peerDisconnect",
  roomConnection = "roomConnection",
  roomLeave = "roomLeave",
  messageSend = "messageSend",
  disconnect = "disconnect",
  stream = "stream",
  call = "call",
  gameUpdate = "gameUpdate",
  socketDisconnect = "socketDisconnect",
  userAudioStatus = "userAudioStatus",
  userVideoStatus = "userVideoStatus",
  userStreamStatus = "userStreamStatus",
  startNight = "startNight",
  startDay = "startDay",
  updateSpeaker = "updateSpeaker",
  wakeUp = "wakeUp",
}
